apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # Match the label from the deployment
  ports:
    - protocol: TCP
      port: 80       # Expose the service on port 80
      targetPort: 5000  # Forward traffic to port 5000 on the pods
  type: nodeport  # Use LoadBalancer to expose the service externally (you can also use NodePort if needed)
